{{- if and .Values.networkPolicies.enabled (ne .Release.Namespace "gitlab") }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-runner-to-kube-api-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: gitlab-runner
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: {{ default "0.0.0.0/0" .Values.networkPolicies.controlPlaneCidr }}
            {{- if eq (default "0.0.0.0/0" .Values.networkPolicies.controlPlaneCidr) "0.0.0.0/0" }}
            except:
              - 169.254.169.254/32
            {{- end }}
    - ports:
      {{- if .Values.networkPolicies.kubeapiPort }}
        - protocol: TCP
          port: {{ .Values.networkPolicies.kubeapiPort }}
      {{- else }}
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 6443
      {{- end }}
{{- end }}
