{{- if .Values.upstream.metrics.enabled }}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: monitoring-metrics-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ printf "%s-upstream" (include "gitlab-runner.fullname" .) }}
  action: ALLOW
  rules:
    - to:
      - operation:
          ports: [{{ .Values.upstream.metrics.port | quote }}]
{{- end }}
