{{ if .Values.metrics.enabled -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "gitlab-runner.fullname" . }}
  labels:
    app: {{ include "gitlab-runner.fullname" . }}
    chart: {{ include "gitlab-runner.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    release: "{{ .Release.Name }}"
  ports:
  - name: metrics
    port: 9252
{{- end }}