{
 "title": "Gitlab Runner Metrics",
 "description": "Gitlab runners metrics with kubernetes executor",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "app",
    "query": {
     "query": "label_values(gitlab_runner_api_request_statuses_total, app)"
    }
   }
  ]
 },
 "panels": [
  { "title": "About $app", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "app" },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=\"https://about.gitlab.com/images/press/logo/jpg/gitlab-logo-gray-stacked-rgb.jpg\"/>"
   }
  },
  {
   "title": "Runner version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitlab_runner_version_info{app=~\"^$app$\"}"
    }
   ]
  },
  {
   "title": "Concurrent setting",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gitlab_runner_concurrent{app=~\"^$app$\"}"
    }
   ]
  },
  {
   "title": "Runner limit setting",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gitlab_runner_limit{app=~\"^$app$\"}",
     "legendFormat": "{{runner}}"
    }
   ]
  },
  {
   "title": "Process max virtual mem",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_max_bytes{app=~\"^$app$\"}",
     "legendFormat": "{{runner}}"
    }
   ]
  },
  {
   "title": "Process max open fd",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_max_fds{app=~\"^$app$\"}",
     "legendFormat": "{{runner}}"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Total number of api requests",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "delta(gitlab_runner_api_request_statuses_total{app=~\"^$app$\"} [2m])",
     "legendFormat": "{{app}} : {{endpoint}} : {{status}}"
    }
   ]
  },
  {
   "title": "The number of caught errors",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "delta(gitlab_runner_errors_total{app=~\"^$app$\"} [2m])",
     "legendFormat": "{{app}} : {{level}}"
    }
   ]
  },
  {
   "title": "kubernertes-jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "sum(gitlab_runner_jobs{job=~\"kubernetes-pods\", state=\"running\",app=~\"^$app$\"}) by (app,job,executor_stage,stage)",
     "legendFormat": "{{app}} : {{job}} : {{executor_stage}} : {{stage}}"
    }
   ]
  },
  { "title": "Concurrency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "The current number of concurrent requests for a new job",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "gitlab_runner_request_concurrency{app=~\"^$app$\"}",
     "legendFormat": "{{app}} : {{runner}}"
    }
   ]
  },
  {
   "title": "Counter tracking exceeding of request concurrency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "delta(gitlab_runner_request_concurrency_exceeded_total{app=~\"^$app$\"} [2m])",
     "legendFormat": "{{app}} : {{ runner}} "
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": " CPU time spent (user and system)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "s", "label": "rate" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{app=~\"^$app$\"} [2m])",
     "legendFormat": "{{app}} "
    }
   ]
  },
  {
   "title": "Number of open file descriptors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{app=~\"^$app$\"}",
     "legendFormat": "{{app}} "
    }
   ]
  },
  {
   "title": "Virtual memory size in bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "decbytes", "label": "usage" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{app=~\"^$app$\"}",
     "legendFormat": "{{app}} "
    }
   ]
  },
  {
   "title": "Resident memory size in bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "decbytes", "label": "usage" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{app=~\"^$app$\"}",
     "legendFormat": "{{app}} "
    }
   ]
  }
 ]
}